credentialsFile: 'credentials.yaml'

notifier:
  enabled: true
  urls:
    - 'gotify://gotify.example.com/token'

defaultParams:
  outFormat: output/{{ .ChannelID }}/{{ .Date }} {{ .Title }}.{{ .Ext }}
  remux: false
  remuxFormat: 'mp4'
  concat: true
  scanDirectory: 'output'
  eligibleForCleaningAge: '3h'
  keepIntermediates: false
  deleteCorrupted: true
  extractAudio: true
  labels: {}

channels:
  'admin':
