credentialsFile: 'credentials.yaml'
cachedCredentialsFile: 'withny-dl.json'

defaultParams:
  outFormat: output/{{ .ChannelID }}/{{ .Date }} {{ .Title }}.{{ .Ext }}
  remux: false
  remuxFormat: 'mp4'
  concat: true
  scanDirectory: 'output'
  eligibleForCleaningAge: '3h'
  keepIntermediates: false
  deleteCorrupted: true
  extractAudio: true
  labels: {}

channels:
  # An empty string will download every live channels.
  '':
    # Ignore specific channels.
    ignore:
      - 'admin'
