services:
  withny:
    image: ghcr.io/darkness4/withny-dl:latest
    restart: unless-stopped
    command: [watch, -c, /config/config.yaml]
    ports:
      - 3000:3000
    user: '${UID}:${GID}'
    volumes:
      - ./credentials.yaml:/secrets/credentials.yaml:ro
      - ./config.yaml:/config/config.yaml:ro
      - ./output:/output
      - withny_cache:/tmp
    mem_reservation: 256m
    mem_limit: 1g
