services:
  withny:
    image: ghcr.io/darkness4/withny-dl:latest
    restart: unless-stopped
    command: [watch, -c, /config/config.yaml]
    ports:
      - 3000:3000
    user: '${UID}:${GID}'
    volumes:
      # credentials.txt contains "example" as username and "password" as password, in base64.
      - ./credentials.txt:/secrets/credentials.txt:ro
      - ./config.yaml:/config/config.yaml:ro
      - ./output:/output
    mem_reservation: 256m
    mem_limit: 1g
