apiVersion: v1
kind: ConfigMap
metadata:
  name: withny-config
data:
  config.yaml: |

    credentialsFile: '/secrets/credentials.yaml'

    defaultParams:
      outFormat: /output/{{ .ChannelID }}/{{ .Date }} {{ .Title }}.{{ .Ext }}
      remux: false
      concat: true
      scanDirectory: '/output'
      eligibleForCleaningAge: '3h'
      keepIntermediates: false
      deleteCorrupted: true
      extractAudio: true

    channels:
      # An empty string means download'em all!
      '':
