apiVersion: v1
kind: ConfigMap
metadata:
  name: withny-config
data:
  config.yaml: |

    credentialsFile: '/secrets/credentials.yaml'

    notifier:
      gotify:
        enabled: true
        endpoint: https://gotify.example.com
        token: 'random'

    defaultParams:
      outFormat: /output/{{ .ChannelID }}/{{ .Date }} {{ .Title }}.{{ .Ext }}
      waitForLive: true
      remux: false
      remuxFormat: mp4
      concat: true
      keepIntermediates: false
      scanDirectory: '/output'
      eligibleForCleaningAge: '48h'
      deleteCorrupted: true
      extractAudio: true

    channels:
      'admin':
        labels: {}
