# It is not recommended to use a secret directly.
# Instead use a secret manager like sealed-secrets or external-secrets.
apiVersion: v1
kind: Secret
metadata:
  name: credentials-secret
type: Opaque
stringData:
  credentials.yaml: |
    username: admin
    password: admin
    # token: "ey..."
    # refreshToken: "abc..."
