name: Contract Testing CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '**.c'
      - '**.h'
      - 'Dockerfile*'
      - '.github/workflows/contract-test.yaml'
      - 'go.*'
      - 'Makefile'
  pull_request:
    branches:
      - 'main'
      - 'release/*'
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: ${{ github.workflow }}

jobs:
  test:
    name: Contract Test withny-dl
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download build-essential
        run: |
          sudo apt update -y
          sudo apt install -y build-essential libavformat-dev libavcodec-dev libavutil-dev

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false
          cache-dependency-path: go.sum

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d%H%M%S")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Download all Go modules
        run: |
          go mod download

      - name: Restore secret
        env:
          WITHNY_CACHED_TOKEN: ${{ secrets.WITHNY_CACHED_TOKEN }}
        run: |
          if [ "$WITHNY_CACHED_TOKEN" != "dummy" ]; then
            echo "$WITHNY_CACHED_TOKEN" > /tmp/withny-dl-test.b64.json
            base64 -d /tmp/withny-dl-test.b64.json > /tmp/withny-dl-test.json
          fi

      - name: test
        env:
          WITHNY_ACCESS_TOKEN: ${{ secrets.WITHNY_ACCESS_TOKEN }}
          WITHNY_REFRESH_TOKEN: ${{ secrets.WITHNY_REFRESH_TOKEN }}
        run: go test -v -tags=contract -timeout=30s github.com/Darkness4/withny-dl/withny/api

      - name: Save secret
        if: always()
        run: |
          base64 /tmp/withny-dl-test.json > /tmp/withny-dl-test.b64.json
          gh secret set WITHNY_CACHED_TOKEN < /tmp/withny-dl-test.b64.json
